# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'third-party-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for third-party-iOS

  # Google
  pod 'GoogleSignIn'

  # Facebook
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'

  # Twitter
  pod 'TwitterKit'

  # Yahoo
  pod 'YJLoginSDK'

  # Line
  pod 'LineSDKSwift'

  target 'third-party-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'third-party-iOSUITests' do
    # Pods for testing
  end

end
